apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-stable
  labels:
    app: product-service
    version: stable
    tier: backend
    component: microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-service
      version: stable
  template:
    metadata:
      labels:
        app: product-service
        version: stable
        tier: backend
        component: microservice
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: product-service
        image: ghcr.io/amine7119/microservices-pipeline/product-service:phase4-v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: PORT
          value: "8000"
        - name: VERSION
          value: "stable"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: product-service-secrets
              key: mongo-uri
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3