apiVersion: v1
kind: Service
metadata:
  name: product-service-canary
  labels:
    app: product-service
    deployment-strategy: canary
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: product-service  # Routes to BOTH stable and canary versions
---
apiVersion: v1
kind: Service  
metadata:
  name: product-service-stable-only
  labels:
    app: product-service
    deployment-strategy: stable-only
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: product-service
    version: stable  # Routes only to stable version
---
apiVersion: v1
kind: Service
metadata:
  name: product-service-canary-only
  labels:
    app: product-service
    deployment-strategy: canary-only
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: product-service
    version: canary  # Routes only to canary version