apiVersion: v1
kind: Secret
metadata:
  name: order-service-secrets
  labels:
    app: order-service
type: Opaque
data:
  # Base64 encoded values
  database-url: cG9zdGdyZXNxbDovL29yZGVyOm9yZGVyQG9yZGVyZGI6NTQzMi9vcmRlcnM=  # postgresql://order:order@orderdb:5432/orders
  rabbitmq-url: YW1xcDovL2d1ZXN0Omd1ZXN0QHJhYmJpdG1xOjU2NzIv  # amqp://guest:guest@rabbitmq:5672/