# Chaos Mesh Installation
# Version: 2.6.3
apiVersion: v1
kind: Namespace
metadata:
  name: chaos-mesh
---
# Chaos Mesh Helm Values
apiVersion: v1
kind: ConfigMap
metadata:
  name: chaos-mesh-values
  namespace: chaos-mesh
data:
  values.yaml: |
    dashboard:
      enabled: true
      service:
        type: LoadBalancer
      securityMode: true
      env:
        DATABASE_DRIVER: sqlite3
        DATABASE_DATASOURCE: /data/chaos-mesh.db
      persistentVolume:
        enabled: true
        size: 10Gi
    
    controllerManager:
      replicaCount: 3
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 512Mi
      
    chaosDaemon:
      runtime: containerd
      socketPath: /run/containerd/containerd.sock
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 512Mi
    
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 15s
    
    webhook:
      certManager:
        enabled: true
      
    dnsServer:
      enabled: true
      
    metrics:
      enabled: true
      
    # Security settings
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 1000
    
    # Multi-cloud support
    cloudProvider: 
      enabled: true
      aws:
        enabled: true
      gcp:
        enabled: true
      azure:
        enabled: false