apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: microservices-pod-failure
  namespace: chaos-mesh
spec:
  action: pod-failure
  mode: random-max-percent
  value: "50"
  duration: "60s"
  selector:
    namespaces:
      - microservices
    labelSelectors:
      "app": "api-gateway"