apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: test-experiment
  namespace: chaos-mesh
spec:
  action: pod-kill
  mode: fixed
  value: "1"
  selector:
    namespaces:
      - default
    labelSelectors:
      run: "test-pod"
  duration: "30s"