apiVersion: v1
kind: Secret
metadata:
  name: product-service-secrets
  labels:
    app: product-service
type: Opaque
data:
  # Base64 encoded MongoDB connection string
  mongo-uri: bW9uZ29kYjovL21vbmdvOjI3MDE3L3Byb2R1Y3Rz  # mongodb://mongo:27017/products