apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
    tier: backend
    component: microservice
spec:
  selector:
    app: product-service
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP