name: 🐛 Bug Report
description: Create a report to help us improve the microservices deployment pipeline
title: "[BUG]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below with as much detail as possible.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have read the troubleshooting documentation
          required: true
        - label: I am using the latest version of the project
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Frontend (React/Vue)
        - API Gateway (Node.js)
        - User Service (Python)
        - Product Service (Go)
        - Order Service (Node.js)
        - Kubernetes Infrastructure
        - CI/CD Pipeline
        - Monitoring & Observability
        - Security Components
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: In which environment did you encounter this bug?
      options:
        - Local Development (Docker Compose)
        - Local Kubernetes (Kind)
        - Development Environment
        - Staging Environment
        - Production Environment
        - CI/CD Pipeline
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Execute command '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened, including error messages
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please paste any relevant logs, error messages, or screenshots
      placeholder: |
        ```
        Paste logs here
        ```
      render: shell

  - type: textarea
    id: system-info
    attributes:
      label: System Information
      description: Information about your system
      placeholder: |
        - OS: [e.g. Ubuntu 22.04, macOS 13.0, Windows 11]
        - Docker Version: [e.g. 24.0.7]
        - Kubernetes Version: [e.g. 1.28.0]
        - Node.js Version: [e.g. 18.17.0]
        - Python Version: [e.g. 3.11.0]
        - Go Version: [e.g. 1.21.0]
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Bug Severity
      description: How severe is this bug?
      options:
        - Critical (System down, data loss, security vulnerability)
        - High (Major feature broken, significant impact)
        - Medium (Minor feature broken, workaround available)
        - Low (Cosmetic issue, no functional impact)
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Browser (if frontend issue): [e.g. Chrome 118.0]
        - Configuration changes made
        - Recent updates or changes
        - Related issues or PRs
        - Possible solutions you've tried

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help fix this issue?
      options:
        - label: I'd like to work on fixing this bug
        - label: I need guidance on how to fix this
        - label: I can provide additional testing or information