apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-flags
  namespace: default
data:
  flags.json: |
    {
      "features": {
        "new_checkout_flow": {
          "enabled": false,
          "rolloutPercentage": 0
        },
        "premium_features": {
          "enabled": true,
          "rolloutPercentage": 100
        },
        "beta_dashboard": {
          "enabled": true,
          "rolloutPercentage": 25
        },
        "dark_mode": {
          "enabled": true,
          "rolloutPercentage": 50
        }
      }
    }