apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
  labels:
    app: user-service
type: Opaque
data:
  # Base64 encoded values (these are examples - replace with real values)
  database-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc0Bob3N0OjU0MzIvdXNlcmRi  # postgresql://user:pass@host:5432/userdb
  jwt-secret: c3VwZXJfc2VjdXJlX2p3dF9zZWNyZXRfa2V5XzEyMw==  # super_secure_jwt_secret_key_123