apiVersion: v1
kind: Service
metadata:
  name: api-gateway-blue-green
  labels:
    app: api-gateway
    deployment-strategy: blue-green
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: api-gateway
    version: blue  # Initially points to blue deployment
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-preview
  labels:
    app: api-gateway
    deployment-strategy: preview
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: api-gateway
    version: green  # Always points to green deployment for testing