apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-green
  labels:
    app: api-gateway
    version: green
    tier: backend
    component: gateway
spec:
  replicas: 0  # Start with 0 replicas - will scale up during deployment
  selector:
    matchLabels:
      app: api-gateway
      version: green
  template:
    metadata:
      labels:
        app: api-gateway
        version: green
        tier: backend
        component: gateway
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: api-gateway
        image: ghcr.io/amine7119/microservices-pipeline/api-gateway:phase4-v2  # New version
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: NODE_ENV
          value: "production"
        - name: VERSION
          value: "green"
        - name: USER_SERVICE_URL
          value: "http://user-service:3000"
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service:8000"
        - name: ORDER_SERVICE_URL
          value: "http://order-service:3001"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3