apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices-dev

resources:
- ../../base/api-gateway
- ../../base/user-service  
- ../../base/product-service
- ../../base/order-service
- ../../base/frontend
- ../../infrastructure/namespaces
- ../../infrastructure/rbac
- ../../infrastructure/network-policies
- ../../infrastructure/ingress.yaml

commonLabels:
  environment: development
  managed-by: argocd

images:
- name: ghcr.io/microservices-pipeline/api-gateway
  newTag: dev-latest
- name: ghcr.io/microservices-pipeline/user-service
  newTag: dev-latest
- name: ghcr.io/microservices-pipeline/product-service
  newTag: dev-latest
- name: ghcr.io/microservices-pipeline/order-service
  newTag: dev-latest
- name: ghcr.io/microservices-pipeline/frontend
  newTag: dev-latest

replicas:
- name: api-gateway
  count: 1
- name: user-service
  count: 1
- name: product-service
  count: 1
- name: order-service
  count: 1
- name: frontend
  count: 1