name: Simple Container Builds

on:
  workflow_dispatch:
  push:
    branches: [ 'feature/phase4-advanced-deployment' ]

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push frontend
      uses: docker/build-push-action@v5
      with:
        context: ./services/frontend
        push: true
        tags: ghcr.io/amine7119/microservices-pipeline/frontend:dev-latest

  build-api-gateway:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push api-gateway
      uses: docker/build-push-action@v5
      with:
        context: ./services/api-gateway
        push: true
        tags: ghcr.io/amine7119/microservices-pipeline/api-gateway:dev-latest

  build-user-service:
    runs-on: ubuntu-latest
    needs: build-api-gateway
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push user-service
      uses: docker/build-push-action@v5
      with:
        context: ./services/user-service
        push: true
        tags: ghcr.io/amine7119/microservices-pipeline/user-service:dev-latest

  build-product-service:
    runs-on: ubuntu-latest
    needs: build-user-service
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push product-service
      uses: docker/build-push-action@v5
      with:
        context: ./services/product-service
        push: true
        tags: ghcr.io/amine7119/microservices-pipeline/product-service:dev-latest

  build-order-service:
    runs-on: ubuntu-latest
    needs: build-product-service
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push order-service
      uses: docker/build-push-action@v5
      with:
        context: ./services/order-service
        push: true
        tags: ghcr.io/amine7119/microservices-pipeline/order-service:dev-latest