apiVersion: v1
kind: ServiceAccount
metadata:
  name: microservices-sa
  namespace: microservices-dev
  labels:
    app.kubernetes.io/name: microservices
    app.kubernetes.io/component: service-account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: microservices-sa
  namespace: microservices-staging
  labels:
    app.kubernetes.io/name: microservices
    app.kubernetes.io/component: service-account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: microservices-sa
  namespace: microservices
  labels:
    app.kubernetes.io/name: microservices
    app.kubernetes.io/component: service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: microservices-dev
  name: microservices-role
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: microservices-staging
  name: microservices-role
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: microservices
  name: microservices-role
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: microservices-binding
  namespace: microservices-dev
subjects:
- kind: ServiceAccount
  name: microservices-sa
  namespace: microservices-dev
roleRef:
  kind: Role
  name: microservices-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: microservices-binding
  namespace: microservices-staging
subjects:
- kind: ServiceAccount
  name: microservices-sa
  namespace: microservices-staging
roleRef:
  kind: Role
  name: microservices-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: microservices-binding
  namespace: microservices
subjects:
- kind: ServiceAccount
  name: microservices-sa
  namespace: microservices
roleRef:
  kind: Role
  name: microservices-role
  apiGroup: rbac.authorization.k8s.io